set (groot,'DefaultAxesFontSize' ,20,'DefaultAxesLineWidth' , 1, ...
    'DefaultLineLineWidth' , 3,'DefaultPatchLineWidth' , 2, ...
    'defaultTextInterpreter', 'latex','DefaultLegendFontSize',20,...
    'DefaultLegendInterpreter', 'latex', 'DefaultLegendFontSizeMode',...
    'manual');